language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: gJs30fxuSTTG1J+7ipGi5pv76d8RKYsaWRc9Kqf6wED6kQB+8Q9q7w8fE1/meqRkLtRgMyHccq4DFc0F+i2vt8UJePBHBMHsY576aExVNSDVPt5reWH30u1F3rPCYRjz+jaWLJ9bMA7v1wzL+jrn4AMwHbAl9rpIJfb9W79sBnKYQyKTzJV2XS6JKaOwtcmT3ZnnJnl7Azm+jnbnBjmjXdSi/ADl/u5KpQQLmDeKKe5cUPCHGLtqEoKzBkis3o/Ph8/Yyx3eTnyuCh7Vi8p3ti27E6Uau6FxdvBsiyxIiEk6MK+xvyBFs++zKMT/B1XiVxpVzGU3bDi1OmwsUQH//QNM57AoH/Km+ateljrb/weB4ITYfTj33e1BAw1h3LQzwsufK7v5rk1uR4E5KvVL2va7K1sailHgu5r025yHbjYiiNP8B83FZD9rRtE2Iuchp1PgbX5YicVIhfH5cvBD5UQXOXcVtiAK3KpEladAh6o+hQ5yxVzgGvrTh1xCFfUFmhifPRs+Vt8KUTkNBHWkV/UXsWxPABxCakYfwsCdnROMF+XTjIgZJM4DFteCMysMCNSOWp2tckvr0i8SPtEnVfqK+yQ35HrxVh0bIfhpRIcKWFGRcZWbsb6afZYStcsOrlrtZ7aK+Ow+3G96iLNE5op4nDEBXPkX3nlkpkWF2BQ=
  - secure: XMLBoOho08x4iO56j8SEdku7LeMJwp1VcaxtXKWwVaW7/djVUIULJL+OaI1axL81x1qhwv7ExnLBhYG7ulzQ3PFZXvh5rnRisn+3ZLec6d+VLHxrmPd3RcLVTuAQCL3cA41d0WktUZ6KGaFI1kPxyTS1BRC8JRHdW1ib9Ii4qvMnQOXAejB62xP/ufdlVWCnqnNiXiPTtFlbSR9zMfrCXZkU/ZbEh/L/Ehwe9TZOEJMI+RlVrWc1Jc/c0jMZE68g96BsQ5T+pLkKOBGaugsWFFVX2AGCGPiT3qRWDsVDvOPO58CHMNUWK2UU9PS5ukISKm0sQ5ZXotiq/NyXF/T34u+hgq4kQafCNv+fTQ+U3YRB3Ui7P4lCPsda5ERijOmGjEyWudbe0r+RO7SaVoJkBZWappYyu10LCLDup6G1qx26oO8yn/Idb2uMF4BwFz4bRedF2HFllAx36t5DdQdMEtukXAOin+OJrdmnJ45kOvwWExwMiRGOsepg8jNzrre1OyAcCji6dwf+xmTwk2Dwg8Ba54MlqZNTUoHeWqd4wTbbT1hJi6048sEjdNE0xhchhvrBiot1x8MYy3r91nQD3N56+Rf3my9q8S8MhZnl7o1GadOnQnLve/fy+O560D5FqZyY5zoyDTGfLYZIG9wBYTYiPoHcgrcMoMJAlcEc76U=
